#!/usr/bin/env bash
# Check if the number of arguments is less than 3 or 4

if [ "$#" -lt 3 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME [PATH_TO_SSH_KEY]"
    exit 1
elif [ "$#" -eq 3 ]; then
    # Transfer the file without using a specific SSH key
    scp "$1" "$3@$2:~/"
else
    # Transfer the file using a specific SSH key
    scp -i "$4" "$1" "$3@$2:~/"
fi
