#!/usr/bin/env bash
# Install Nginx
sudo apt-get install -y nginx

# Start Nginx service
sudo service nginx start

# Enable Nginx to start on boot
sudo systemctl enable nginx

# Create or overwrite index.html with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html

# Create custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Remove any existing conflicting lines in the Nginx default server block
sudo sed -i '/rewrite \^\/redirect_me/d' /etc/nginx/sites-available/default
sudo sed -i '/error_page 404 \/404.html/d' /etc/nginx/sites-available/default

# Add redirect rule to Nginx default server block
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default

# Add custom 404 error page to Nginx default server block
sudo sed -i "/listen 80 default_server;/a error_page 404 /404.html;" /etc/nginx/sites-available/default

# Remove any existing conflicting lines in the main Nginx configuration file
sudo sed -i '/add_header X-Served-By/d' /etc/nginx/nginx.conf

# Add custom header to Nginx configuration
sudo sed -i '14a \\tadd_header X-Served-By '"${HOSTNAME}"';' /etc/nginx/nginx.conf

# Check Nginx configuration for syntax errors
sudo nginx -t

# Restart Nginx to apply changes if configuration is successful
if [ $? -eq 0 ]; then
    sudo service nginx restart
else
    echo "Nginx configuration test failed."
fi

# Check Nginx service status
sudo service nginx status

