#!/usr/bin/env bash
sudo apt update
sudo apt upgrade -y

# Install HAProxy
sudo apt install -y haproxy

# Configure HAProxy
#sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

sudo bash -c 'cat > /etc/haproxy/haproxy.cfg <<EOF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 34.207.58.74:80 check
    server web-02 54.160.99.220:80 check

EOF'

# Enable HAProxy init script
sudo systemctl enable haproxy
sudo systemctl restart haproxy
