#!/usr/bin/env bash
#script that print Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line
counter=1

while [ $counter -le 10 ]
do
    if [ $counter -eq 9 ]; then
	    echo "Best School"
	    echo "hi"
    else
	    echo "Best School"
    fi
    ((counter++))
done
