#!/usr/bin/env bash
#script that
counter=1

while [ $counter -le 20 ]
do
	echo -n "$counter "
	case $counter in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
		*)
      			echo ""  # Just move to the next line
      			;;
	esac
	((counter++))
done
