#!/bin/env bash 
PRIVATE_KEY="school"
PASSPHRASE="betty"
BITS=4096

# Create RSA key pair
openssl genpkey -algorithm RSA -out $PRIVATE_KEY -aes256 -pass pass:$PASSPHRASE -pkeyopt rsa_keygen_bits:$BITS
openssl rsa -pubout -in $PRIVATE_KEY -out ${PRIVATE_KEY}.pub -passin pass:$PASSPHRASE

echo "RSA key pair created. Private key: $PRIVATE_KEY, Public key: ${PRIVATE_KEY}.pub"

